<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ProduceReferenceAssembly>False</ProduceReferenceAssembly>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <AppendRuntimeIdentifierToOutputPath>false</AppendRuntimeIdentifierToOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <IsPublishable>False</IsPublishable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_ReSharper.Caches\**" />
    <EmbeddedResource Remove="_ReSharper.Caches\**" />
    <None Remove="_ReSharper.Caches\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Docfx.App" Version="2.78.5" />
    <PackageReference Include="System.Drawing.Common" Version="10.0.7" />
  </ItemGroup>

</Project>
